# Generated by Django 3.2.8 on 2021-11-26 03:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatRoom', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='avatar.svg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
